server {
    listen 80;
    listen [::]:80;
    server_name pizda.asia www.pizda.asia;

    root /usr/share/nginx/html;
    index index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Кеширование для статических файлов (оптимизация загрузки)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|mp4)$ {
        expires max;
        log_not_found off;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
